### ISSUE TITLE
Persist swap phase in db

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1079]
Basics: all measures to handle failures/attacks in a swap flow gracefully (#942 ) require the node to know which phase the swap is in. This issue is about persisting the `SwapPhase` & `SwapState` (reason to be in that state as per [types.ts](https://github.com/ExchangeUnion/xud/blob/master/lib/swaps/types.ts#L12)) in db after each step in the protocol, read it after restarts/crashes and display swaps in critical phases in `getinfo`.

### Status Quo
Currently these [`SwapPhase`](https://github.com/ExchangeUnion/xud/blob/master/lib/constants/enums.ts#L57)s are already present, but only success/failure is persisted in the `swapdeals` table in `xud.db`:
```
export enum SwapPhase {
  /** The swap has been created locally. */
  SwapCreated = 0,
  /** The swap has been sent to a peer to request approval. */
  SwapRequested = 1,
  /** The terms of the swap have been agreed to, and we will attempt to execute it. */
  SwapAgreed = 2,
  /**
   * We have commanded swap client to send payment according to the agreed terms. The payment (and swap)
   * could still fail due to no route with sufficient capacity, lack of cooperation from the
   * receiver or any intermediary node along the route, or an unexpected error from swap client.
   */
  SendingAmount = 3,
  /** We have received the agreed amount of the swap, and the preimage is now known to both sides. */
  AmountReceived = 4,
  /** The swap has been formally completed and both sides have confirmed they've received payment. */
  SwapCompleted = 5,
}
```

### TODO
- [x] Persist each phase change in db, **only continue with next step if phase was successfully stored in db**
- [x] New swap phases as per [Swap Flow](https://github.com/ExchangeUnion/xud/pull/1025#issuecomment-502047537) without breaking changes:
```
export enum SwapPhase {
  /** Role Taker: The swap has been created locally. */
  SwapCreated = 0,

  /** Role Taker: The swap, stating currencies and amounts has been sent to the maker to request approval. */
  SwapRequested = 1,

  /**
  * Role Maker: We set the agreed currency and amount (can be be less than requested) of the swap and we successfully sent a `SwapAccepted` packet with these details to the Taker. Or successfully declined swap with `SwapFailed` packet.*/
  * Role Taker: The currency and an amount of the swap have been agreed to or declined (we received the `SwapAccepted` or `SwapFailed` packet from the Maker)
*/
  SwapAgreed = 2,

  /**
   * Role Taker: We have commanded swap client to send payment (leg 1) according to the agreed currency and amount of the received `SwapAccepted` packet. This can fail due to no route with sufficient capacity, lack of cooperation from the eceiver or any intermediary node along the route, or an unexpected error from swap client. Result stored in `state`.
   * Role Maker: Sending Payment (leg 2) AFTER received taker's payment (phase 4). Can fail due to no route, see above.
   */
  SendingPayment = 3,

  /** 
   * Role Taker: We have received the agreed amount of the swap as an in-flight HTLC (leg 2)
   * Role Maker: We have received the agreed amount of the swap as an in-flight HTLC (leg 1)
   */
  PaymentReceived = 4,

  /** 
   * Role Taker: Role Taker: Successfully revealed preimage and claimed payment on leg 2.
   * Role Maker: Successfully claimed payment on leg 1 (after phase 7).
   */
  PaymentClaimed = 6,

  /**  Role Maker: Successfully received preimage from Taker. */
  PreimageReceived = 7,

 /** Role Taker+Maker: The swap has been formally completed and both sides have confirmed they've received payment OR collaboratively failed the swap. */
  SwapCompleted = 5,
}
```
- [ ] Display swaps in stages which are NOT `5` with some details (tbd) in `getinfo` to bring these to the users's attention. Then user can use ID to search the log for details.

**Comment by erkarl** [comment]
The new phases look good. I'm thinking we might want to separate the phases so that they are specific to the role `SendingPaymentTaker`, `SendingPaymentMaker` instead of `SendingPayment`.

I believe this would make the debugging experience better/more readable.
